### ISSUE TITLE
error in BackEndApplication.java.

### ISSUE THREAD

**Issue by cecm9113** [MicrosoftDocs/azure-docs.es-es#685]
when I put the connection string in the project "BackEndApplication.java", it generate the next error: 

Calling direct method...
Exception in thread "main" java.lang.IllegalArgumentException: SharedAccessKeyName cannot be null or empty
	at com.microsoft.azure.sdk.iot.service.IotHubConnectionStringBuilder.validate(IotHubConnectionStringBuilder.java:164)
	at com.microsoft.azure.sdk.iot.service.IotHubConnectionStringBuilder.parse(IotHubConnectionStringBuilder.java:129)
	at com.microsoft.azure.sdk.iot.service.IotHubConnectionStringBuilder.createConnectionString(IotHubConnectionStringBuilder.java:42)
	at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceMethod.createFromConnectionString(DeviceMethod.java:47)
	at com.microsoft.docs.iothub.samples.BackEndApplication.main(BackEndApplication.java:37)

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 72cc606c-5806-0a5b-cffb-6328608f9f9c
* Version Independent ID: 58fdfdf8-7194-6f67-2611-d97175d305e2
* Content: [Inicio rápido: Control de un dispositivo desde Azure IoT Hub con Java](https://docs.microsoft.com/es-es/azure/iot-hub/quickstart-control-device-java#feedback)
* Content Source: [articles/iot-hub/quickstart-control-device-java.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/iot-hub/quickstart-control-device-java.md)
* Service: **iot-hub**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by srvbpigh** [comment]
Hello, @cecm9113
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
